# SPDX-FileCopyrightText: 2026 OpenOstler contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""A simulated node for NodeSource tests and UI work: it replays the node fixtures
(``tests/fixtures/node/*.jsonl``, generated by the firmware's host tests) through an MQTT
broker with the node's own connection shape: client id = device, retained ``status``
``online`` with an ``offline`` will, keep-alive 10 s (``ostler-firmware`` ``main/net.c``).

Test and dev only: it fabricates the timing of every value it publishes.
"""
from __future__ import annotations

import base64
import json
import threading
import time
from pathlib import Path

from openostler.mqtt import StdlibMqttClient, Will

FIXTURES = Path(__file__).resolve().parent / "fixtures" / "node"
VECTORS = ("td5-vectors.jsonl", "slabs-vectors.jsonl")
VID, DEVICE = "d2-bench", "node"


def load(name: str) -> "list[dict]":
    """One fixture file's messages; ``payload`` as bytes (``payload_b64`` decoded)."""
    out = []
    for line in (FIXTURES / name).read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        d = json.loads(line)
        d["payload"] = (base64.b64decode(d["payload_b64"]) if "payload_b64" in d
                        else d["payload"].encode("utf-8"))
        out.append(d)
    return out


def case(name: str) -> dict:
    """A hand-written ``status-power.jsonl`` line by its ``case``."""
    for d in load("status-power.jsonl"):
        if d["case"] == name:
            return d
    raise KeyError(name)


def vss_messages(names=VECTORS) -> "list[dict]":
    return [d for n in names for d in load(n) if "/vss/" in d["topic"]]


def topic(kind: str, vid: str = VID, device: str = DEVICE) -> str:
    return f"ostler/v1/{vid}/{device}/{kind}"


class FakeNode:
    """Connects as the node and publishes; :meth:`run_loop` replays the vectors forever
    with fresh ``t_us``/``ts`` (for ``tests/e2e_server.py --node``)."""

    def __init__(self, host: str, port: int, *, device: str = DEVICE, vid: str = VID,
                 keep_alive: int = 10, boot: int = 7) -> None:
        self.device, self.vid, self.boot = device, vid, boot
        self.client = StdlibMqttClient(device, keep_alive=keep_alive, will=Will(
            topic("status", vid, device), b"offline", qos=1, retain=True))
        self.host, self.port = host, port
        self._stop = threading.Event()
        self._t0 = time.monotonic()

    def connect(self, online: bool = True) -> "FakeNode":
        self.client.connect(self.host, self.port)
        if online:
            self.client.publish(topic("status", self.vid, self.device), b"online", 1, True)
        return self

    def send(self, msg: dict, *, retain: "bool | None" = None) -> None:
        self.client.publish(msg["topic"], msg["payload"], msg.get("qos", 0),
                            msg.get("retain", False) if retain is None else retain)

    def send_vss(self, leaf: str, value, *, name: str, source: str, t_us: int,
                 c: str = "proven", unit: str = "", ts: "str | None" = None,
                 boot: "int | None" = None, **extra) -> None:
        body = {"value": value, "unit": unit, "ts": ts, "t_us": t_us,
                "boot": self.boot if boot is None else boot, "source": source,
                "name": name, "c": c, "raw": value, **extra}
        if boot is False:
            body.pop("boot")
        self.client.publish(topic(f"vss/{leaf}", self.vid, self.device),
                            json.dumps(body).encode(), 0, True)

    def run_loop(self, interval: float = 0.05) -> None:
        msgs = vss_messages()
        self.send(case("awake"))
        while not self._stop.is_set():
            for m in msgs:
                if self._stop.is_set():
                    return
                body = json.loads(m["payload"])
                now = time.time()
                body["t_us"] = int((time.monotonic() - self._t0) * 1e6) + 1_000_000
                body["ts"] = time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime(now)) + \
                    f".{int(now * 1000) % 1000:03d}Z"
                try:
                    self.client.publish(m["topic"], json.dumps(body).encode(), 0, True)
                except OSError:
                    return
                self._stop.wait(interval)

    def start_loop(self, interval: float = 0.05) -> None:
        threading.Thread(target=self.run_loop, args=(interval,), daemon=True).start()

    def stop(self) -> None:
        self._stop.set()
        self.client.disconnect()


__all__ = ["DEVICE", "FakeNode", "VID", "case", "load", "topic", "vss_messages"]
