# SPDX-FileCopyrightText: 2026 OpenOstler contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""A simulated node for NodeSource tests and UI work: it replays the node fixtures
(``tests/fixtures/node/*.jsonl``; the vector runs and the lifecycle are generated by the
firmware's host tests, the rest is hand-written for what the node cannot publish yet)
through an MQTT
broker with the node's own connection shape: client id = device, retained ``status``
``online`` with an ``offline`` will, keep-alive 10 s (``ostler-firmware`` ``main/net.c``).

Test and dev only: it fabricates the timing of every value it publishes.
"""
from __future__ import annotations

import base64
import json
import threading
import time
from pathlib import Path

from openostler.mqtt import StdlibMqttClient, Will

FIXTURES = Path(__file__).resolve().parent / "fixtures" / "node"
VECTORS = ("td5-vectors.jsonl", "slabs-vectors.jsonl")
LIFECYCLE = "lifecycle.jsonl"
VID, DEVICE = "d2-bench", "node"
_STATE = ("status", "power", "manifest", "role")


def load(name: str) -> "list[dict]":
    """One fixture file's messages; ``payload`` as bytes (``payload_b64`` decoded)."""
    out = []
    for line in (FIXTURES / name).read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        d = json.loads(line)
        d["payload"] = (base64.b64decode(d["payload_b64"]) if "payload_b64" in d
                        else d["payload"].encode("utf-8"))
        out.append(d)
    return out


def _kind(d: dict) -> str:
    return d["topic"].split("/")[4]


def node_lifecycle() -> "list[dict]":
    """The firmware's lifecycle dump (``lifecycle.jsonl``): online, start, both modules, a
    reconnect's re-announce, then a clean sleep (gate claim released, power and status
    ``asleep``)."""
    return load(LIFECYCLE)


def node_awake() -> "list[dict]":
    """The real node's retained state while it runs (from ``lifecycle.jsonl``, up to its
    first claim release): ``status`` online, ``power`` awake, the latest ``manifest`` (the
    K-line item ``ok``) and the gate claim, one message per topic in publish order."""
    last: "dict[str, dict]" = {}
    for d in node_lifecycle():
        if _kind(d) == "role" and not d["payload"]:
            break
        if _kind(d) in _STATE:
            last.pop(d["topic"], None)
            last[d["topic"]] = d
    return list(last.values())


def node_sleep() -> "list[dict]":
    """The real node's clean sleep, as published (``lifecycle.jsonl`` from its first claim
    release): the gate claim released, ``power`` asleep, then ``status`` asleep."""
    msgs = node_lifecycle()
    i = next(i for i, d in enumerate(msgs) if _kind(d) == "role" and not d["payload"])
    return [d for d in msgs[i:] if _kind(d) in _STATE]


def node_shutdown(name: str = "td5-vectors.jsonl") -> "list[dict]":
    """The end of a vector run: the gate claim released and ``power`` shutting_down; the
    status is not changed (the node stops without sleeping)."""
    msgs = load(name)
    i = next(i for i, d in enumerate(msgs) if _kind(d) == "role" and not d["payload"])
    return [d for d in msgs[i:] if _kind(d) in _STATE]


def case(name: str) -> dict:
    """One ``status`` or ``power`` message by name. ``online``, ``awake`` and ``asleep``
    are the firmware's own (``lifecycle.jsonl``), ``shutting_down`` the end of the Td5
    vector run; ``offline`` (the broker's will), ``held``, ``waking`` and ``off`` are
    hand-written (``status-power.jsonl``): the node does not publish them yet."""
    real = {"online": lambda: next(d for d in node_lifecycle() if _kind(d) == "status"),
            "awake": lambda: next(d for d in node_lifecycle() if _kind(d) == "power"),
            "asleep": lambda: next(d for d in node_sleep() if _kind(d) == "power"),
            "shutting_down": lambda: next(d for d in node_shutdown() if _kind(d) == "power")}
    if name in real:
        return {"case": name, **real[name]()}
    for d in load("status-power.jsonl"):
        if d["case"] == name:
            return d
    raise KeyError(name)


def vss_messages(names=VECTORS) -> "list[dict]":
    return [d for n in names for d in load(n) if "/vss/" in d["topic"]]


def tap_messages(name: str = "td5-vectors.jsonl") -> "list[dict]":
    """The raw-tap header and batches of one vector run (``tap/<session>/meta|data``)."""
    return [d for d in load(name) if "/tap/" in d["topic"]]


def cluster_messages(case: str = "cluster") -> "list[dict]":
    """A cluster's messages of one ``case`` (NodeSource P3). ``cluster``: the real node
    awake (:func:`node_awake`) and the hand-written devices around it (``cluster.jsonl``:
    a guardian, a brain, a relay module and a sensor node, with their claims).
    ``node_asleep``: the node releases its hand-written vehicle-role claims (when
    ``node_roles`` was fed) and then sleeps as the firmware does (:func:`node_sleep`).
    Other cases are hand-written only: ``node_roles`` (the node declaring and holding the
    parked broker and time roles, which this firmware does not), ``gate_conflict`` (a
    second node claiming the K-line gate), ``guardian_takes_pbroker``."""
    hand = [d for d in load("cluster.jsonl") if d["case"] == case]
    if case == "cluster":
        return node_awake() + hand
    if case == "node_asleep":
        return [d for d in load("cluster.jsonl") if d["case"] == "node_roles_released"] + \
            node_sleep()
    return hand


def time_event(t_us: int, utc_ns: int, source: str = "sntp") -> bytes:
    """A raw-tap ``time`` event payload as the node writes it: CBOR ``{t_us, utc_ns,
    source, err_us: null}``, shortest-form heads (raw-tap amendment of 2026-10-06)."""
    def head(major: int, n: int) -> bytes:
        for info, size in ((24, 1), (25, 2), (26, 4), (27, 8)):
            if n < 24:
                return bytes([major << 5 | n])
            if n < 1 << (8 * size):
                return bytes([major << 5 | info]) + n.to_bytes(size, "big")
        raise ValueError(n)

    def text(t: str) -> bytes:
        return head(3, len(t)) + t.encode()

    return (head(5, 4) + text("t_us") + head(0, t_us) + text("utc_ns") + head(0, utc_ns)
            + text("source") + text(source) + text("err_us") + b"\xf6")


def topic(kind: str, vid: str = VID, device: str = DEVICE) -> str:
    return f"ostler/v1/{vid}/{device}/{kind}"


class FakeNode:
    """Connects as the node and publishes; :meth:`run_loop` replays the vectors forever
    with fresh ``t_us``/``ts`` (for ``tests/e2e_server.py --node``)."""

    def __init__(self, host: str, port: int, *, device: str = DEVICE, vid: str = VID,
                 keep_alive: int = 10, boot: int = 7) -> None:
        self.device, self.vid, self.boot = device, vid, boot
        self.client = StdlibMqttClient(device, keep_alive=keep_alive, will=Will(
            topic("status", vid, device), b"offline", qos=1, retain=True))
        self.host, self.port = host, port
        self._stop = threading.Event()
        self._t0 = time.monotonic()

    def connect(self, online: bool = True) -> "FakeNode":
        self.client.connect(self.host, self.port)
        if online:
            self.client.publish(topic("status", self.vid, self.device), b"online", 1, True)
        return self

    def send(self, msg: dict, *, retain: "bool | None" = None) -> None:
        self.client.publish(msg["topic"], msg["payload"], msg.get("qos", 0),
                            msg.get("retain", False) if retain is None else retain)

    def send_vss(self, leaf: str, value, *, name: str, source: str, t_us: int,
                 c: str = "proven", unit: str = "", ts: "str | None" = None,
                 boot: "int | None" = None, **extra) -> None:
        body = {"value": value, "unit": unit, "ts": ts, "t_us": t_us,
                "boot": self.boot if boot is None else boot, "source": source,
                "name": name, "c": c, "raw": value, **extra}
        if boot is False:
            body.pop("boot")
        self.client.publish(topic(f"vss/{leaf}", self.vid, self.device),
                            json.dumps(body).encode(), 0, True)

    def run_loop(self, interval: float = 0.05) -> None:
        msgs = vss_messages()
        tap = tap_messages()
        self.send(case("awake"))
        seq = 0
        while not self._stop.is_set():
            seq = self._send_tap(tap, seq)
            for m in msgs:
                if self._stop.is_set():
                    return
                body = json.loads(m["payload"])
                now = time.time()
                body["t_us"] = int((time.monotonic() - self._t0) * 1e6) + 1_000_000
                body["ts"] = time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime(now)) + \
                    f".{int(now * 1000) % 1000:03d}Z"
                try:
                    self.client.publish(m["topic"], json.dumps(body).encode(), 0, True)
                except OSError:
                    return
                self._stop.wait(interval)

    def _send_tap(self, tap: "list[dict]", seq: int) -> int:
        """The fixture's tap header and batches, renumbered to continue ``seq`` and timed
        now, so a looping node's tap has no gaps or repeats; its ``time`` events are
        re-stamped to map the new ``t_us`` to the wall clock now."""
        from openostler.node.tap import encode_record, is_time_event, parse_records

        t_us = int((time.monotonic() - self._t0) * 1e6) + 1_000_000
        for m in tap:
            if m["topic"].endswith("/meta"):
                self.send(m)
                continue
            records, _ = parse_records(m["payload"])
            out = []
            for r in records:
                payload = r.payload
                if is_time_event(r):
                    utc_ns = time.time_ns() - (int((time.monotonic() - self._t0) * 1e6)
                                               + 1_000_000 - t_us) * 1000
                    payload = time_event(t_us, utc_ns)
                out.append(encode_record(type(r)(t_us, seq, r.type, r.bus, r.dir, r.proto,
                                                 r.flags, payload)))
                seq, t_us = seq + 1, t_us + 1000
            try:
                self.client.publish(m["topic"], b"".join(out), 1, False)
            except OSError:
                break
        return seq

    def start_loop(self, interval: float = 0.05) -> None:
        threading.Thread(target=self.run_loop, args=(interval,), daemon=True).start()

    def stop(self) -> None:
        self._stop.set()
        self.client.disconnect()


__all__ = ["DEVICE", "FakeNode", "VID", "case", "cluster_messages", "load", "node_awake",
           "node_lifecycle", "node_shutdown", "node_sleep", "tap_messages", "time_event", "topic",
           "vss_messages"]
