# SPDX-FileCopyrightText: 2026 OpenOstler contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""The VSS namespace seam (ADR-0016, specs/2026-10-06-u0-seams-design.md §A).

``src/openostler/metrics.json`` and ``vss_leaves.json`` are generated by
``tools/build_metrics.py`` from ``vss/ostler.vspec`` over the pinned release in
``vss/upstream/``. These tests check the committed files and the ``metric`` key on signal
store records. The freshness check needs vss-tools (dev-only, Python >= 3.11); CI
installs it and also runs ``python tools/build_metrics.py --check``.
"""
from __future__ import annotations

import importlib.util
import json
import re
from pathlib import Path

import pytest

from openostler import metrics, signals
from openostler.metrics import PATH_RE, is_known, load_metrics, metric_info, vss_version
from tests.fake_pack import FAKE_PACK

ROOT = Path(__file__).resolve().parents[1]
UPSTREAM = ROOT / "vss" / "upstream"
HAS_VSS_TOOLS = importlib.util.find_spec("vss_tools") is not None


def _unit_keys() -> "set[str]":
    """Top-level keys of the pinned units.yaml (stdlib parse: one ``key:`` per line)."""
    keys = set()
    for line in (UPSTREAM / "units.yaml").read_text(encoding="utf-8").splitlines():
        m = re.match(r"^([^\s#][^:]*):\s*$", line)
        if m:
            keys.add(m.group(1).strip().strip("'\""))
    return keys


def _store_records(signals_dir: Path) -> "list[tuple[str, dict]]":
    out = []
    for f in sorted(Path(signals_dir).glob("*.json")):
        for r in json.loads(f.read_text(encoding="utf-8")):
            out.append((f"{f.stem}.{r.get('name')}", r))
    return out


# ---- the pin and the vendored release ------------------------------------------------ #

def test_vss_pin_is_6_1():
    assert (ROOT / "vss" / "VERSION").read_text(encoding="utf-8").strip() == "6.1"
    assert vss_version() == "6.1"
    assert json.loads(metrics.LEAVES_FILE.read_text(encoding="utf-8"))["vss_version"] == "6.1"


def test_vendored_release_files_are_present_with_their_licence():
    for name in ("vss.json", "model.vspec", "units.yaml", "quantities.yaml", "LICENSE",
                 "README.md"):
        assert (UPSTREAM / name).is_file(), name
    assert "Mozilla Public License Version 2.0" in (UPSTREAM / "LICENSE").read_text(encoding="utf-8")
    size = sum(p.stat().st_size for p in UPSTREAM.iterdir())
    assert size < 5 * 1024 * 1024


def test_units_parse_matches_yaml_when_available():
    yaml = pytest.importorskip("yaml", reason="PyYAML comes with vss-tools (dev-only)")
    assert _unit_keys() == set(yaml.safe_load((UPSTREAM / "units.yaml").read_text(encoding="utf-8")))


# ---- metrics.json --------------------------------------------------------------------- #

@pytest.mark.skipif(not HAS_VSS_TOOLS, reason="vss-tools is not installed (dev-only, Python "
                    ">= 3.11): pip install -e '.[dev]'; CI installs it")
def test_metrics_json_is_current():
    from tools import build_metrics

    out = build_metrics.generate()
    for path, text in out.items():
        assert path.read_text(encoding="utf-8") == text, \
            f"{path.name} is stale: run python tools/build_metrics.py"


def test_metrics_json_is_sorted_and_well_formed():
    doc = json.loads(metrics.METRICS_FILE.read_text(encoding="utf-8"))
    rows = doc["metrics"]
    paths = [r["path"] for r in rows]
    assert paths == sorted(paths) and len(paths) == len(set(paths))
    for r in rows:
        assert PATH_RE.match(r["path"]), r["path"]
        assert set(r) == {"path", "type", "datatype", "unit", "description", "ostler_role",
                          "aliases", "extension"}
        assert r["type"] in ("sensor", "actuator", "attribute")
        assert r["extension"] == r["path"].startswith("Vehicle.Ostler.")
        assert set(r["aliases"]) <= {"ovms", "ha_device_class", "ha_state_class", "obdb"}


def test_every_unit_is_a_verbatim_key_of_the_pinned_units_file():
    units = _unit_keys()
    assert {"km/h", "rpm", "Celsius", "V", "percent", "kPa"} <= units
    for r in load_metrics().values():
        assert r["unit"] is None or r["unit"] in units, (r["path"], r["unit"])
    leaves = json.loads(metrics.LEAVES_FILE.read_text(encoding="utf-8"))["leaves"]
    bad = {p: u for p, u in leaves.items() if u is not None and u not in units}
    assert not bad


def test_aliases_are_unique_per_kind():
    for kind in ("ovms", "obdb"):
        seen: "dict[str, str]" = {}
        for r in load_metrics().values():
            v = r["aliases"].get(kind)
            if v is not None:
                assert v not in seen, f"{kind} {v!r} on {seen.get(v)} and {r['path']}"
                seen[v] = r["path"]


def test_fuel_is_never_an_ovms_battery_metric():
    for r in load_metrics().values():
        ovms = r["aliases"].get("ovms", "")
        assert ovms != "v.b.soc", r["path"]
        if r["path"].startswith("Vehicle.Powertrain.FuelSystem."):
            assert not ovms.startswith("v.b."), r["path"]
        if r["path"].startswith("Vehicle.Powertrain.CombustionEngine."):
            assert not ovms.startswith("v.m."), "v.m.* is the motor, not the engine"


def test_common_set_and_extensions_are_present():
    m = load_metrics()
    assert m["Vehicle.Speed"]["unit"] == "km/h"
    assert m["Vehicle.Speed"]["aliases"]["ovms"] == "v.p.speed"
    assert m["Vehicle.Powertrain.CombustionEngine.EngineCoolant.Temperature"]["unit"] == "Celsius"
    roles = {r["ostler_role"] for r in m.values()}
    assert {"speed", "rpm", "coolant", "battery", "fuel", "health"} <= roles
    for p in ("Vehicle.Ostler.Diagnostics.MilOn", "Vehicle.Ostler.Diagnostics.DtcCount"):
        assert m[p]["extension"] and m[p]["ostler_role"] == "health"


def test_metric_info_and_is_known():
    assert metric_info("Vehicle.Speed")["aliases"]["obdb"] == "speed"
    # a standard leaf the overlay does not annotate: known, with its upstream unit
    info = metric_info("Vehicle.Powertrain.CombustionEngine.Torque")
    assert info is not None and info["unit"] == "Nm" and info["aliases"] == {}
    assert is_known("Vehicle.Powertrain.CombustionEngine.Torque")
    assert is_known("Vehicle.Ostler.Diagnostics.MilOn")
    for bad in ("Vehicle.Nope", "Vehicle", "Vehicle.Powertrain", "vehicle.speed", "", None, 3,
                "Vehicle.OBD.Speed"):
        assert not is_known(bad), bad
    assert metric_info("Vehicle.Nope") is None


# ---- the signal store's optional metric ---------------------------------------------- #

def test_signal_metric_is_loaded_and_written_through(tmp_path, monkeypatch):
    monkeypatch.setattr(signals, "_DIR", tmp_path)
    signals.upsert_field("m", {"name": "speed", "lid": "0D", "offset": 0, "kind": "u8",
                               "metric": "Vehicle.Speed"})
    signals.upsert_field("m", {"name": "temp", "lid": "1A", "offset": 0, "metric": ""})
    rows = signals.load_records("m")
    assert rows[0]["metric"] == "Vehicle.Speed" and "metric" not in rows[1]
    by = {s.name: s for s in signals.load_signals("m")}
    assert by["speed"].metric == "Vehicle.Speed" and by["temp"].metric is None
    with pytest.raises(ValueError):
        signals.upsert_field("m", {"name": "x", "lid": "01", "offset": 0, "metric": "Vehicle.Nope"})
    assert len(signals.load_records("m")) == 2


def test_fake_pack_metrics_resolve():
    recs = _store_records(FAKE_PACK.signals_dir)
    with_metric = [(k, r) for k, r in recs if "metric" in r]
    assert with_metric, "the fake pack carries at least one metric"
    for key, r in with_metric:
        assert is_known(r["metric"]), (key, r["metric"])


@pytest.mark.needs_pack
def test_d2_pack_metrics_resolve():
    pytest.importorskip("d2diag")
    from openostler.pack import active_pack

    pack = active_pack()
    assert pack.id != FAKE_PACK.id
    for key, r in _store_records(pack.signals_dir):
        if r.get("metric"):
            assert is_known(r["metric"]), (key, r["metric"])
