#!/usr/bin/env python3
"""Regenerate INDEX.md from frontmatter across the repo.

Walks the repository, reads each manifest-eligible file's frontmatter,
and writes a manifest table (path/area/status/version/updated/summary) plus
static reading paths. INDEX.md is generated — do not edit it by hand. Stdlib only.

Usage:
    python3 skill/scripts/build_index.py
"""

from __future__ import annotations

import datetime
import sys

import _frontmatter as fm

# Display order for areas in the manifest.
AREA_ORDER = ["root", "docs", "references", "hardware", "decisions", "specs"]

READING_PATHS = """\
## Reading paths

- **New here?** Read [README.md](README.md), then [docs/README.md](docs/README.md).
- **Changing code?** Read [CONSTITUTION.md](CONSTITUTION.md), then
  [docs/architecture.md](docs/architecture.md).
- **Going to the car?** Read [references/test_plan.md](references/test_plan.md) and
  [references/protocol_state_handoff.md](references/protocol_state_handoff.md).
- **Sniffing with a NanoCom?** Read [decisions/](decisions/CLAUDE.md) ADR-0005 and
  [references/reference_tool_sniff_plan.md](references/reference_tool_sniff_plan.md).
- **Want the why behind a choice?** Read [decisions/](decisions/CLAUDE.md).
"""


def cell(value: str) -> str:
    """Make a value safe for a single Markdown table cell."""
    text = " ".join(str(value).split())
    return text.replace("|", "\\|")


def main() -> int:
    root = fm.repo_root()
    today = datetime.date.today().isoformat()

    rows = []
    errors = 0
    for rel in fm.iter_manifest_files(root):
        data, err = fm.load(f"{root}/{rel}")
        if err:
            print(f"WARN {rel}: {err}", file=sys.stderr)
            errors += 1
            continue
        rows.append(
            {
                "path": rel,
                "area": data.get("area", "?"),
                "status": data.get("status", "?"),
                "version": data.get("version", "?"),
                "updated": data.get("updated", "?"),
                "summary": data.get("summary", ""),
            }
        )

    def sort_key(r):
        area = r["area"]
        order = AREA_ORDER.index(area) if area in AREA_ORDER else len(AREA_ORDER)
        return (order, r["path"])

    rows.sort(key=sort_key)

    lines = [
        "---",
        "title: Index",
        "area: root",
        "status: stable",
        "version: 1.0",
        f"updated: {today}",
        "summary: >",
        "  Generated manifest of every document in this repo — path, area,",
        "  status, version, updated date, and a ~100-token summary — plus reading paths.",
        "---",
        "",
        "# Index",
        "",
        "> Generated by `skill/scripts/build_index.py`. Do not edit by hand.",
        "",
        f"{len(rows)} documents.",
        "",
        "## Manifest",
        "",
        "| Path | Area | Status | Version | Updated | Summary |",
        "| ---- | ---- | ------ | ------- | ------- | ------- |",
    ]
    for r in rows:
        lines.append(
            "| {path} | {area} | {status} | {version} | {updated} | {summary} |".format(
                path=f"[{r['path']}]({r['path']})",
                area=cell(r["area"]),
                status=cell(r["status"]),
                version=cell(r["version"]),
                updated=cell(r["updated"]),
                summary=cell(r["summary"]),
            )
        )
    lines += ["", READING_PATHS]

    out = "\n".join(lines).rstrip() + "\n"
    with open(f"{root}/INDEX.md", "w", encoding="utf-8") as fh:
        fh.write(out)

    print(f"Wrote INDEX.md with {len(rows)} entries.")
    if errors:
        print(f"{errors} file(s) skipped due to frontmatter errors.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
