# SPDX-FileCopyrightText: 2026 OpenOstler contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""The canonical signal namespace: COVESA VSS paths (ADR-0016). Stdlib only.

Two committed files, both generated by ``tools/build_metrics.py`` (dev-only, vss-tools)
and shipped as package data:

* ``metrics.json``: every VSS leaf the overlay ``vss/ostler.vspec`` names (the common set
  plus the ``Vehicle.Ostler.*`` extensions), with its type, datatype, VSS unit key,
  description, Home role (``ostler_role``) and aliases (OVMS, Home Assistant, OBDb).
* ``vss_leaves.json``: every leaf path of the pinned upstream VSS tree with its unit.

A signal-store record may carry an optional ``metric`` (a VSS path); it must be
:func:`is_known`. Packs never repeat the metadata kept here.
"""
from __future__ import annotations

import json
import re
from functools import lru_cache
from pathlib import Path

_HERE = Path(__file__).resolve().parent
METRICS_FILE = _HERE / "metrics.json"
LEAVES_FILE = _HERE / "vss_leaves.json"

# A VSS path: dot-separated UpperCamelCase-ish segments under the root ``Vehicle``.
PATH_RE = re.compile(r"^Vehicle(\.[A-Za-z0-9_]+)+$")


@lru_cache(maxsize=1)
def _metrics_doc() -> dict:
    return json.loads(METRICS_FILE.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def _leaves() -> "dict[str, str | None]":
    return json.loads(LEAVES_FILE.read_text(encoding="utf-8"))["leaves"]


@lru_cache(maxsize=1)
def load_metrics() -> "dict[str, dict]":
    """``metrics.json`` as ``{path: entry}`` (cached; treat the entries as read-only)."""
    return {m["path"]: m for m in _metrics_doc()["metrics"]}


def vss_version() -> str:
    """The pinned VSS release (``vss/VERSION``), e.g. ``"6.1"``."""
    return str(_metrics_doc()["vss_version"])


def metric_info(path: str) -> "dict | None":
    """The ``metrics.json`` entry for ``path``; for a standard VSS leaf the overlay does
    not annotate, a minimal ``{path, unit, aliases: {}, extension: False}``; else None."""
    entry = load_metrics().get(path)
    if entry is not None:
        return entry
    leaves = _leaves()
    if path in leaves:
        return {"path": path, "unit": leaves[path], "ostler_role": None, "aliases": {},
                "extension": False}
    return None


def is_known(path: object) -> bool:
    """True if ``path`` is in ``metrics.json`` or a leaf of the pinned upstream VSS tree."""
    if not isinstance(path, str) or not PATH_RE.match(path):
        return False
    return path in load_metrics() or path in _leaves()


__all__ = ["load_metrics", "metric_info", "is_known", "vss_version", "PATH_RE"]
